server:
  port: 8081
spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
dubbo:
  application:
    name: my-provider
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    address: nacos://10.211.55.3:8848
    protocol: dubbo
  protocol:
    name: dubbo
    port: 20890