server:
  port: 8085
spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
dubbo:
  application:
    name: annotation-provider-demo
  registry:
    address: nacos://10.211.55.3:8848
  protocol:
    name: dubbo
    serialization: fst
#    port: 20890